- name: Setup Tekton cli for AWS EKS cluster
  hosts: Application_Group
  become: true
  tasks: 
    - name: Install boto3
      ansible.builtin.pip:
        name: boto3
        state: present

    - name: Upgrade awscli
      ansible.builtin.pip:
        name: awscli
        state: present
        extra_args: --upgrade

    - name: Check whether aws creds folder
      stat:
        path: /home/ubuntu/.aws
      register: aws_creds_folder

    - name: Setup aws creds
      block:
        - name: Make directory for aws creds
          shell: "mkdir /home/ubuntu/.aws"

        - name: Copy AWS creds
          ansible.builtin.copy:
            src: /home/ubuntu/.aws/credentials
            dest: /home/ubuntu/.aws/credentials

        - name: Copy AWS config file
          ansible.builtin.copy:
            src: /home/ubuntu/.aws/config
            dest: /home/ubuntu/.aws/config
      when: aws_creds_folder.stat.exists == False

    - name: Update using apt  
      apt: 
        update_cache: true

    - name: Update using apt get
      apt:
        update_cache: true
        force_apt_get: true

    - name: Install awscli,gnupg
      apt:
        name: 
          - awscli
          - gnupg
        state: present

    - name: Get kubectl binary
      get_url:
        url: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl

    - name: Set execution permissions for kubectl
      file:
        path: /usr/local/bin/kubectl
        mode: +x

    - name: Update kubeconfig file
      become: false
      shell: aws eks update-kubeconfig --name '{{k8s.cluster_name}}'

    - name: Update using apt
      apt:
        update_cache: true

    - name: Add tekton keys
      shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA

    - name: Add tekton cli to apt list
      shell: echo "deb http://ppa.launchpad.net/tektoncd/cli/ubuntu eoan main"|sudo tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list

    - name: Update using apt
      apt:
        update_cache: true

    - name: Install tektoncd cli
      apt:
        name: tektoncd-cli
        state: present