- name: Setup Jenkins
  hosts: Jenkins_Group
  become: true
  tasks:
    - name: Update using apt
      apt:
        update_cache: yes

    - name: Update using apt-get
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Install gnupg,software-properties-common,curl
      apt:
        name:
          - gnupg
          - software-properties-common
          - curl
        state: present
        force_apt_get: yes

    - name: Get Terraform Repository key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Terraform Repository key
      shell: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

    - name: Update using apt-get
      apt:
        update_cache: true
        force_apt_get: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present
        force_apt_get: yes
